name: Build and Deploy Calendar PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'templates/**'
      - 'styles/**'
      - 'build.py'
      - 'requirements.txt'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build PDF
        run: |
          python build.py --year 2025 --out /tmp/LWSD-2025-26-onepage.pdf
          cp /tmp/LWSD-2025-26-onepage.pdf /tmp/HoraceMann-PTSA-2025-26-Calendar.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HoraceMann-PTSA-Calendar
          path: /tmp/HoraceMann-PTSA-2025-26-Calendar.pdf
      - name: Deploy PDF to GitHub Pages branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Try to fetch the gh-pages branch, create if it doesn't exist
          git fetch origin gh-pages:refs/remotes/origin/gh-pages || true
          
          # Create or checkout gh-pages branch
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
            git pull origin gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf . || true
            echo "# Calendar PDFs" > README.md
          fi
          
          # Copy the PDF with a stable name for easy linking
          cp /tmp/HoraceMann-PTSA-2025-26-Calendar.pdf calendar.pdf
          cp /tmp/HoraceMann-PTSA-2025-26-Calendar.pdf "calendar-$(date +%Y%m%d).pdf"
          
          # Create a simple index.html for web viewing
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Horace Mann PTSA Calendar 2025-26</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  h1 { color: #C40A0C; }
                  .download-btn { 
                      background: #C40A0C; 
                      color: white; 
                      padding: 10px 20px; 
                      text-decoration: none; 
                      border-radius: 5px; 
                      display: inline-block;
                      margin: 10px 0;
                  }
              </style>
          </head>
          <body>
              <h1>Horace Mann PTSA Calendar 2025-26</h1>
              <p>Latest version of the calendar:</p>
              <a href="calendar.pdf" class="download-btn">Download Calendar PDF</a>
              <br><br>
              <iframe src="calendar.pdf" width="100%" height="800px"></iframe>
          </body>
          </html>
          EOF
          
          # Commit and push
          git add .
          git commit -m "Update calendar PDF from commit ${{ github.sha }}" || echo "No changes to commit"
          git push origin gh-pages