name: Build Calendar PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'templates/**'
      - 'styles/**'
      - 'build.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: |
          python build.py --year 2025 --out build/LWSD-2025-26-onepage.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LWSD-2025-26-onepage
          path: build/LWSD-2025-26-onepage.pdf
